# Generated by Django 4.2.20 on 2026-05-17 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRerunJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bulk_job_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('job_type', models.CharField(choices=[('program_rerun', 'Program Rerun'), ('new_org', 'New Org'), ('individual', 'Individual')], default='individual', max_length=16)),
                ('source_course_key', models.CharField(max_length=255)),
                ('target_course_key', models.CharField(max_length=255, unique=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_rerun_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bulk_job_id', 'status'], name='openedx_bul_bulk_jo_c5b26c_idx'), models.Index(fields=['target_course_key'], name='openedx_bul_target__c9b2e9_idx')],
            },
        ),
    ]
