# Generated by Django 4.2.20 on 2026-05-27 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openedx_bulk_rerun_ext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursererunjob',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BulkRerunBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('program_rerun', 'Program Rerun'), ('new_org', 'New Org'), ('individual', 'Individual')], max_length=16)),
                ('is_dry_run', models.BooleanField(default=False)),
                ('target_run', models.CharField(max_length=64)),
                ('prog_id', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='pending', max_length=16)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_rerun_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coursererunjob',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='openedx_bulk_rerun_ext.bulkrerunbatch'),
        ),
        migrations.CreateModel(
            name='CourseRerunLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('ok', 'OK'), ('warn', 'Warn'), ('err', 'Error')], default='info', max_length=8)),
                ('message', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='openedx_bulk_rerun_ext.coursererunjob')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='openedx_bul_job_id_48e2a8_idx')],
            },
        ),
    ]
