# Generated by Django 4.2.20 on 2026-05-27 19:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_bulk_rerun_ext', '0002_coursererunjob_position_bulkrerunbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursererunjob',
            name='settings_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursererunlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CourseRerunSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_start', models.DateTimeField()),
                ('course_end', models.DateTimeField()),
                ('enrollment_start', models.DateTimeField()),
                ('enrollment_end', models.DateTimeField()),
                ('pacing', models.CharField(choices=[('instructor', 'Instructor-paced'), ('self', 'Self-paced')], default='instructor', max_length=16)),
                ('course_mode', models.CharField(choices=[('honor', 'Honor'), ('audit', 'Audit'), ('verified', 'Verified')], default='honor', max_length=16)),
                ('cert_display', models.CharField(choices=[('early_no_info', 'Early (no info)'), ('early_with_info', 'Early (with info)'), ('end', 'End of course')], default='early_no_info', max_length=32)),
                ('create_cert', models.BooleanField(default=True)),
                ('student_gen_cert', models.BooleanField(default=True)),
                ('cert_on_dashboard', models.BooleanField(default=True)),
                ('gating_mode', models.CharField(choices=[('disabled', 'Disabled'), ('copy', 'Copy from source'), ('template', 'Apply template'), ('custom', 'Custom (not implemented)')], default='disabled', max_length=16)),
                ('gating_template_id', models.CharField(blank=True, default='', max_length=128)),
                ('remove_provisioner_after', models.BooleanField(default=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='openedx_bulk_rerun_ext.bulkrerunbatch')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRerunTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('studio_role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('data_researcher', 'Data Researcher')], default='admin', max_length=32)),
                ('discussion_role', models.CharField(choices=[('discussion_admin', 'Discussion Admin'), ('moderator', 'Moderator'), ('none', 'None')], default='discussion_admin', max_length=32)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='openedx_bulk_rerun_ext.bulkrerunbatch')),
            ],
            options={
                'ordering': ['email'],
                'unique_together': {('batch', 'email')},
            },
        ),
    ]
