# Generated by Django 4.2.30 on 2026-07-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_bulk_rerun_ext', '0008_coursererunmember_org_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkrerunbatch',
            name='rollback_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], default='none', help_text='State of the rollback pass that deletes courses this batch created. Kept separate from status so rollback never disturbs the run-lifecycle state machine.', max_length=16),
        ),
        migrations.AddField(
            model_name='bulkrerunbatch',
            name='rolled_back_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursererunjob',
            name='course_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursererunjob',
            name='rolled_back',
            field=models.BooleanField(default=False),
        ),
    ]
